spring:
  data:
    mongodb:
      database: journaldb
      host: localhost
      port: 27017
      auto-index-creation: true
  main:
    allow-circular-references: true

server:
  port: 8081
  servlet:
    context-path: /api/v1